// Original — no upstream. Regeneration script for src/tools/_register-baseline.json (FR-018, BI-022).
// Future BIs that intentionally add, remove, or rename a tool run `npm run baseline:write` and
// commit the regenerated JSON in the same commit as the registry change. Self-contained — replicates
// the canonicalisation + fingerprint logic from src/tools/_register-baseline.ts inline because
// Node 22.x's --experimental-strip-types cannot resolve the project's `.js`-on-`.ts` import
// aliases. The /speckit-implement quality-gate enforces "writer and verifier produce identical
// fingerprints" via the FR-018 test in src/tools/_register.test.ts.
//
// To roll this script forward without drift: when src/tools/_register-baseline.ts's canonicalJSON
// or sha256 logic changes, mirror the change here. The verifier (the test) is the source of truth
// for fingerprint values; if the script's fingerprints differ, the next `npm run baseline:write`
// will produce a baseline the test rejects — at which point the operator fixes the drift here.

import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { execSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

function sha256(input: string): string {
  return createHash("sha256").update(input, "utf8").digest("hex");
}

function canonicalJSON(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return "[" + value.map(canonicalJSON).join(",") + "]";
  }
  const keys = Object.keys(value as Record<string, unknown>).sort();
  const entries = keys.map(
    (k) => JSON.stringify(k) + ":" + canonicalJSON((value as Record<string, unknown>)[k]),
  );
  return "{" + entries.join(",") + "}";
}

interface ListedTool {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
}

async function dumpRegistryViaVitest(): Promise<ListedTool[]> {
  // We can't import src/server.ts directly under node --experimental-strip-types because the
  // source uses `.js` import-extension aliases for `.ts` files (NodeNext convention). Vitest
  // is the only runtime the project already wires up that resolves those aliases. We delegate
  // by writing a temporary vitest test file that calls createServer + dumps tools/list into
  // a JSON file at a temp path; we read the JSON back here. This indirection costs ~700ms once
  // per regeneration — acceptable for an out-of-band tool.
  const scratch = mkdtempSync(join(tmpdir(), "baseline-writer-"));
  const dumpPath = join(scratch, "tools-list.json");
  const dumperPath = resolve(import.meta.dirname, "..", "src", "tools", "__baseline-dumper.test.ts");
  const dumperSource = `// Auto-generated by scripts/write-register-baseline.ts — safe to delete.
import { writeFileSync } from "node:fs";

import { it } from "vitest";

import { createServer } from "../server.js";

it("dump tools/list to ${dumpPath.replaceAll("\\", "\\\\")}", async () => {
  const { server } = createServer({ registerSignalHandlers: false });
  const handlers = (server as unknown as { _requestHandlers: Map<string, (req: unknown) => Promise<unknown>> })._requestHandlers;
  const listHandler = handlers.get("tools/list");
  if (!listHandler) throw new Error("tools/list handler not registered");
  const result = await listHandler({ method: "tools/list", params: {} });
  writeFileSync(${JSON.stringify(dumpPath)}, JSON.stringify(result, null, 2) + "\\n");
});
`;
  writeFileSync(dumperPath, dumperSource, { encoding: "utf8" });
  try {
    await new Promise<void>((resolveP, rejectP) => {
      const child = spawn(
        "npx",
        ["vitest", "run", "--no-coverage", dumperPath],
        { stdio: "inherit", shell: true },
      );
      child.on("exit", (code) => {
        if (code === 0) resolveP();
        else rejectP(new Error(`vitest exited ${code}`));
      });
      child.on("error", rejectP);
    });
    const payload = JSON.parse(readFileSync(dumpPath, "utf8")) as { tools: ListedTool[] };
    return payload.tools;
  } finally {
    rmSync(dumperPath, { force: true });
    rmSync(scratch, { recursive: true, force: true });
  }
}

async function main(): Promise<void> {
  const tools = await dumpRegistryViaVitest();
  const entries = tools
    .map((t) => ({
      name: t.name,
      descriptionFingerprint: sha256(t.description),
      schemaFingerprint: sha256(canonicalJSON(t.inputSchema)),
    }))
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  let branch = "unknown";
  try {
    branch = execSync("git rev-parse --abbrev-ref HEAD", { encoding: "utf8" }).trim();
  } catch {
    // git not available or not a repo — leave branch as "unknown"
  }
  const payload = {
    schemaVersion: 1 as const,
    generatedFromBranch: branch,
    generatedAt: new Date().toISOString().slice(0, 10),
    tools: entries,
  };
  const outPath = resolve(import.meta.dirname, "..", "src", "tools", "_register-baseline.json");
  writeFileSync(outPath, JSON.stringify(payload, null, 2) + "\n", { encoding: "utf8" });
  process.stderr.write(`Wrote ${entries.length} entries to ${outPath}\n`);
}

await main();
